--!strict
--[=[
	Installer — copies the bundled runtime SDK into the customer's game
	and writes a bootstrap Script that boots it with their refresh token.

	WHY THIS EXISTS
		The plugin's auth half (PluginAuth) talks to Roculus from inside
		Studio so the dev can see "Connected." But for the PUBLISHED game
		to call our backend at runtime, the SDK has to live inside the
		game's own ServerScriptService — that's the only context Roblox
		actually runs server-side scripts. Pairing without installing
		would leave a connected-looking plugin and a silent published
		game.

	WHAT IT WRITES
		ServerScriptService.RoculusBridge          — ModuleScript (the
		                                              entire SDK runtime,
		                                              cloned from the
		                                              plugin's bundled
		                                              EmbeddedRuntime)
		ServerScriptService.RoculusBridgeBootstrap — Script (calls
		                                              Roculus:start
		                                              with the refresh
		                                              token + apiBase)

	REINSTALL SAFETY
		If either name already exists, we destroy it first. So re-pairing
		(with a new token, for example) is idempotent — same names, fresh
		contents.

	UNDOABLE
		Wrapped in ChangeHistoryService waypoints so Ctrl+Z unwinds the
		install. Cheap insurance.

	TOKEN-IN-SOURCE NOTE
		The refresh token is baked into the bootstrap Script's source.
		ServerScriptService isn't replicated to clients so players can't
		read it, but if the .rbxl is committed to public source control
		(GitHub, etc.) the token leaks. Standard credential hygiene —
		same trade-off as embedding a Stripe key in app source.
]=]

local ChangeHistoryService = game:GetService("ChangeHistoryService")
local ServerScriptService = game:GetService("ServerScriptService")

local Installer = {}

local MODULE_NAME = "RoculusBridge"
local BOOTSTRAP_NAME = "RoculusBridgeBootstrap"

local BOOTSTRAP_SOURCE_TEMPLATE = [=[--!strict
--[==[
	Auto-generated by the Roculus Bridge plugin (re-pair via the plugin
	to refresh). Do not edit by hand — your changes are wiped on every
	re-install.

	The refresh token below is the credential the SDK trades for
	short-lived access tokens at runtime via /api/v1/bridge/auth/exchange.
	Keep this file (and your .rbxl) out of public source control.
]==]
local ServerScriptService = game:GetService("ServerScriptService")

local Roculus = require(ServerScriptService:WaitForChild("%s"))

Roculus:start({
	token = "%s",
	apiBase = "%s",
	debug = false,
})
]=]

local function destroyIfPresent(parent: Instance, name: string)
	local existing = parent:FindFirstChild(name)
	if existing then
		existing:Destroy()
	end
end

function Installer.install(embeddedRuntime: Instance, refreshToken: string, apiBase: string): ()
	assert(typeof(embeddedRuntime) == "Instance", "Installer.install: embeddedRuntime must be an Instance")
	assert(type(refreshToken) == "string" and #refreshToken > 0, "Installer.install: refreshToken required")
	assert(type(apiBase) == "string" and #apiBase > 0, "Installer.install: apiBase required")

	ChangeHistoryService:SetWaypoint("Roculus Bridge: installing")

	destroyIfPresent(ServerScriptService, MODULE_NAME)
	destroyIfPresent(ServerScriptService, BOOTSTRAP_NAME)

	-- Clone the bundled runtime tree (a ModuleScript whose source is the
	-- runtime's init.lua, with all sub-modules as children). Rename so
	-- the bootstrap can find it by a stable name.
	local sdk = embeddedRuntime:Clone()
	sdk.Name = MODULE_NAME
	sdk.Parent = ServerScriptService

	-- Write the bootstrap Script. Source has the refresh token + apiBase
	-- substituted in. The %q in the format would auto-escape but we
	-- intentionally use %s + manual escaping so the rendered file reads
	-- like hand-written code; %q wraps in quotes AND escapes which
	-- changes the visible form for humans browsing the script.
	local source = string.format(
		BOOTSTRAP_SOURCE_TEMPLATE,
		MODULE_NAME,
		refreshToken,
		apiBase
	)
	local bootstrap = Instance.new("Script")
	bootstrap.Name = BOOTSTRAP_NAME
	bootstrap.Source = source
	bootstrap.Parent = ServerScriptService

	ChangeHistoryService:SetWaypoint("Roculus Bridge: installed")
end

function Installer.uninstall(): ()
	ChangeHistoryService:SetWaypoint("Roculus Bridge: uninstalling")
	destroyIfPresent(ServerScriptService, MODULE_NAME)
	destroyIfPresent(ServerScriptService, BOOTSTRAP_NAME)
	ChangeHistoryService:SetWaypoint("Roculus Bridge: uninstalled")
end

function Installer.isInstalled(): boolean
	return ServerScriptService:FindFirstChild(MODULE_NAME) ~= nil
		and ServerScriptService:FindFirstChild(BOOTSTRAP_NAME) ~= nil
end

return Installer
